//  NOTES
//  1. This is based on a PSR-11-39 type cell which operates at 8-14mV in air at 1ATM. The middle of the range is 11mV. Adjust this
//     value depending on the type of cell intended for use with the analyser. ADC_GAIN16_CONVERSION_CONSTANT has been mathematially derived.
//  2. These control how much the cell reading can be adjusted with the calibration potentiometer. Default is +/- 50% (50-150%) at midrange
//     on potentiometer.
//  3. These are the typical minimum and maximum values that the chosen potentiometer gives. This has been derived through physical testing
//     of random component samples. If using a different potentiometer from the reference design then test and replace with measured values.

#include "adc_hal.h"
#include "display_hal.h"
#include "system_state.h"
#include "gpio_hal.h"
#include <Wire.h>

constexpr uint32_t CELL_READ_FREQUENCY_MS = 250U;
constexpr uint16_t POT_MIN = 0U;  // See Note 3
constexpr uint16_t POT_MAX = 1100U; // See Note 3
constexpr uint16_t CAL_PERCENT_MIN = 50U; // See Note 2
constexpr uint16_t CAL_PERCENT_MAX = 150U; // See Note 2
constexpr uint16_t MIDRANGE_MV = 11U; // See Note 1
constexpr uint16_t ADC_GAIN16_CONVERSION_CONSTANT = 128U; // Do not change, see Note 1
constexpr uint16_t ADC_REFERENCE_RAW = MIDRANGE_MV * ADC_GAIN16_CONVERSION_CONSTANT; // Do not change, calculated at compile time
constexpr uint16_t ADC_REFERENCE_FO2_X10 = 210U; // FO2 of Air at 1ATM
constexpr uint16_t MAXIMUM_FO2_X10 = 1050U; // Analyser has a maximum FO2 limit of 105%
constexpr uint16_t MAXIMUM_PPO2_X1000 = 16000U;  // Used for MOD calculation (based on 1.6 max)
constexpr uint16_t DEPTH_CORRECTION_FACTOR = 10U; // Convert from ATM to metres
constexpr uint16_t HYPOXIC_THRESHOLD_X10 = 170U;  // 17% set as hypoxic threshold
constexpr uint32_t ONE_SECOND_MS = 1000U;  // 1000ms for timing routines
constexpr uint8_t BUFFER_SIZE_INTEGER_DISPLAY = 4U;  // Used for display formatting
constexpr uint8_t BUFFER_SIZE_FO2_DISPLAY = 6U;  // Used for display formatting



void setup() {
  hw_state_t state = HW_UNINITIALISED;

  Wire.begin();
  pinMode(LED_BUILTIN, OUTPUT);

  //Serial.begin(115200);


  if(!system_state_init()){
    state = HW_STATE_FAILED;
  } else if(display_init() != DISPLAY_STATUS_OK) {
    state = HW_DISPLAY_FAILED;
  } else if (!gpio_init()){
    state = HW_GPIO_INIT_FAILED;
  } else if(adc_init() != ADC_STATUS_OK) {
    state = HW_ADC_INIT_FAILED;
  } else {
    state = HW_OK;
  }

  switch (state) {
    case HW_OK:
      system_state_set_loop_check_time(millis());
      system_state_set_loop_state(STATE_START_UP);
      break;
    case HW_DISPLAY_FAILED:
      failure_state_init(millis());
      system_state_set_loop_state(STATE_FAILED_SAFE);
      break;
    case HW_ADC_INIT_FAILED:
      system_state_set_loop_state(STATE_ADC_FAILED);
      break;
    case HW_GPIO_INIT_FAILED:
      system_state_set_loop_state(STATE_GPIO_FAILED);
      break;
    case HW_STATE_FAILED:
      system_state_set_loop_state(STATE_HW_FAILURE);
      break;
    default:
      system_state_set_loop_state(STATE_FAILED_SAFE);
      break;
  }
}

void loop() {
  loop_state_t state;
  if(system_state_get_loop_state(&state) != SYSTEM_OK){
    system_state_set_loop_state(STATE_FAILED_SAFE);
    return;
  }
  uint32_t now = millis();

  switch (state) {
    case STATE_START_UP:
      fsm_handler_start_up(now);
      break;
    case STATE_READ_CELL:
      fsm_handler_read_cell(now);
      break;
    case STATE_HW_FAILURE: // Error state generated by software issue
      fsm_handler_hw_failure();
      break;
    case STATE_FAILED_SAFE: // Revert to this state if screen unavailable
      fsm_handler_failed_safe(now);
      break;
    case STATE_GPIO_FAILED: // Failure of potentiometer or pin read/write
      fsm_handler_gpio_failed();
      break;
    case STATE_ADC_FAILED:
      fsm_handler_adc_failed();
      break;
    default:
      system_state_set_loop_state(STATE_FAILED_SAFE);
      break;
  }
}

// Functions
//  0. WORK IN PROGRESS -- MOVE TO CORRECT SECTION
//  1. STATE MACHINE HANDLERS
//  2. DISPLAY HELPERS 
//  3. TIME HELPERS
//  4. FO2 CALCULATIONS

// 0. WORK IN PROGRESS -- MOVE TO CORRECT SECTION




// 1. STATE MACHINE HANDLERS

void fsm_handler_gpio_failed(void){
  display_clear();
  display_set_cursor(0, 0);
  display_println("CAL POT");
  display_println("FAILED");
  display_update();
  for(;;){
    yield();
  }
}

void fsm_handler_adc_failed(void){
  display_clear();
  display_set_cursor(0, 0);
  display_println("ADS1115");
  display_println("FAILED");
  display_update();
  for(;;){
    yield();
  }
}

void fsm_handler_start_up(const uint32_t now){
  uint32_t last_time = 0;

  if(system_state_get_loop_check_time(&last_time) != SYSTEM_OK){
    system_state_set_loop_state(STATE_HW_FAILURE);
    return;
  }
  if(has_timer_elapsed(now, last_time, ONE_SECOND_MS)){
    system_state_set_loop_state(STATE_READ_CELL);
    return;
  }
  if(!system_state_get_run_once_flag()){
    display_clear();
    display_set_colour(DISPLAY_WHITE, DISPLAY_BLACK);
    display_set_cursor(0, 0);
    display_print("START");
    display_update();
    system_state_set_run_once_flag(true);
  }
}

void fsm_handler_read_cell(const uint32_t now){
  uint32_t last_check_time = 0U;
  uint16_t raw_reading = 0;
  uint16_t calibration_reading = 0;
  uint16_t fo2 = 0;
  uint16_t mV = 0;
  uint16_t calibrated_fo2;
  uint16_t mod_msw = 0;
  
  if(system_state_get_loop_check_time(&last_check_time) != SYSTEM_OK){
    system_state_set_loop_state(STATE_FAILED_SAFE);
    return;
  }
  if(has_timer_elapsed(now, last_check_time, CELL_READ_FREQUENCY_MS)){
    if(adc_raw_reading(&raw_reading) != ADC_STATUS_OK){
      system_state_set_loop_state(STATE_ADC_FAILED);
      return;
    }
    if(!gpio_read_calibration_pin(&calibration_reading)){
      system_state_set_loop_state(STATE_FAILED_SAFE);
      return;
    }
    if(system_state_set_loop_check_time(now) != SYSTEM_OK){
      system_state_set_loop_state(STATE_FAILED_SAFE);
      return;
    }
    fo2 = convert_raw_to_fo2(raw_reading);
    mV = adc_convert_raw_to_mV(raw_reading);
    calibrated_fo2 = calibrate_value_to_percent(fo2, calibration_reading);
    mod_msw = calculate_mod(calibrated_fo2);
    display_clear();
    display_set_cursor(0, 0);
    print_fo2_to_display(calibrated_fo2);
    print_mod_to_display(mod_msw);
    print_mv_to_display(mV);
    print_pulse_to_display(now);
    display_update();
  }
}

void fsm_handler_hw_failure(void){
  display_clear();
  display_set_cursor(0, 0);
  display_print("HW FAILED");
  display_update();
  for(;;){
    yield();
  }
}

void fsm_handler_failed_safe(const uint32_t now){
  uint32_t last_check_time = failure_state_get_time();


  if(has_timer_elapsed(now, last_check_time, ONE_SECOND_MS)){
    const bool led_on = failure_state_get_led_on();

    digitalWrite(LED_BUILTIN, led_on);
    failure_state_set_led_on(!led_on);
    failure_state_set_time(now);
  }
}

// 2. DISPLAY HELPERS

void print_pulse_to_display(const uint32_t now){
  uint32_t pulse_check_time = 0U;

  if(system_state_get_pulse_on_flag()){
      display_print("+");
  }
  system_state_get_pulse_check_time(&pulse_check_time);
  if(has_timer_elapsed(now, pulse_check_time, ONE_SECOND_MS)){
    system_state_invert_pulse_on_flag();
    system_state_set_pulse_check_time(now);
  }
}

void print_mv_to_display(const uint16_t mV){
  char buffer_mv[BUFFER_SIZE_INTEGER_DISPLAY] = {};

  format_integer_for_display(mV, buffer_mv);
  display_print("Cell");
  if(mV < 10){
    display_print("   ");
  } else if (mV > 99){
    display_print(" ");
  } else {
    display_print("  ");
  }
  display_print(buffer_mv);
  display_println("mV");
}

void print_mod_to_display(const uint16_t mod_msw){
  char buffer_mod[BUFFER_SIZE_INTEGER_DISPLAY] = {};

  format_integer_for_display(mod_msw, buffer_mod);
  display_print("MOD");
  if(mod_msw < 10){
    display_print("   ");
  } else if (mod_msw > 99){
    display_print(" ");
  } else {
    display_print("  ");
  }
  display_print(buffer_mod);
  display_println("msw");
}

void print_fo2_to_display(const uint16_t calibrated_fo2){
  char buffer_fo2[BUFFER_SIZE_FO2_DISPLAY] = {};

  format_fo2_for_display(calibrated_fo2, buffer_fo2);
  display_print("fO2 ");
  if((calibrated_fo2 < HYPOXIC_THRESHOLD_X10) || (calibrated_fo2 >= MAXIMUM_FO2_X10)){
    display_set_colour(DISPLAY_BLACK, DISPLAY_WHITE);
  }
  display_print(buffer_fo2);
  display_println("%");
  display_set_colour(DISPLAY_WHITE, DISPLAY_BLACK);
}

void format_fo2_for_display(uint16_t fo2, char buffer[6]){
  uint16_t integer_part = 0;
  uint16_t temp = 0;
  uint8_t digit = 0;

  if (fo2 > 9999U){
    fo2 = 9999U;
  }
  integer_part = fo2 / 10U;

  /* Hundreds digit */
  temp = integer_part;
  digit = (uint8_t)(temp / 100U);
  buffer[0] = (char)('0' + digit);

  temp %= 100U;

  /* Tens digit */
  digit = (uint8_t)(temp / 10U);
  buffer[1] = (char)('0' + digit);

  /* Units digit */
  digit = (uint8_t)(temp % 10U);
  buffer[2] = (char)('0' + digit);

  buffer[3] = '.';

  /* Tenths digit */
  digit = (uint8_t)(fo2 % 10U);
  buffer[4] = (char)('0' + digit);

  buffer[5] = '\0';

  if (buffer[0] == '0')
  {
    buffer[0] = ' ';
  }

  if ((buffer[0] == ' ') && (buffer[1] == '0'))
  {
    buffer[1] = ' ';
  }
}

void format_integer_for_display(uint16_t value, char buffer[4]){
  uint16_t temp;
  uint8_t pos = 0U;

  if(value > 999U){
    value = 999U;
  }
  if(value >= 100U){
    buffer[pos] = (char)('0' + (uint8_t)(value / 100U));
    pos++;
    value %= 100U;
  }
  if((value >= 10U) || (pos > 0U)){
    buffer[pos] = (char)('0' + (uint8_t)(value / 10U));
    pos++;
    value %= 10U;
  }
  temp = value;
  buffer[pos] = (char)('0' + (uint8_t)temp);
  pos++;
  buffer[pos] = '\0';
}

// 3. TIME HELPERS

bool has_timer_elapsed(const uint32_t current_time, const uint32_t last_time, const uint32_t frequency){
  return (current_time - last_time) >= frequency; // See Note 9
}

// 4. FO2 CALCULATIONS

uint16_t calibrate_value_to_percent(uint16_t raw_reading, uint16_t potentiometer_reading){
  uint16_t calibration_factor = 0;
  uint16_t calibration_range = CAL_PERCENT_MAX - CAL_PERCENT_MIN;
  uint16_t pot_range = POT_MAX - POT_MIN;

  if(potentiometer_reading < POT_MIN){
    potentiometer_reading = POT_MIN;
  }
  if(potentiometer_reading > POT_MAX){
    potentiometer_reading = POT_MAX;
  }
  if(pot_range == 0){
    return raw_reading;
  }
  calibration_factor = CAL_PERCENT_MIN + ((uint32_t)(potentiometer_reading - POT_MIN) * calibration_range) / pot_range;

  return ((uint32_t)raw_reading * calibration_factor) / 100;
}


uint16_t convert_raw_to_fo2(const uint16_t raw_reading){
  const uint32_t numerator = (uint32_t)(raw_reading) * ADC_REFERENCE_FO2_X10;

  return (uint16_t)((numerator + (ADC_REFERENCE_RAW / 2U)) / ADC_REFERENCE_RAW);
}

uint16_t calculate_mod(const uint16_t fo2){
  uint16_t rounded_down = fo2 / DEPTH_CORRECTION_FACTOR * DEPTH_CORRECTION_FACTOR;
  if(rounded_down == 0U){
    return 0U;
  }
  return MAXIMUM_PPO2_X1000 / rounded_down - DEPTH_CORRECTION_FACTOR;
}
